# Generated by Django 5.0.2 on 2024-03-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0002_fooditems_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='food_slug',
            field=models.SlugField(default=None),
            preserve_default=False,
        ),
    ]
