# Generated by Django 5.0.2 on 2024-03-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0003_fooditems_food_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='image_url',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
