# Generated by Django 5.0.2 on 2024-03-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0004_fooditems_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='image_url',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
