# Generated by Django 5.0.2 on 2024-03-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0006_alter_fooditems_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='image_url',
            field=models.CharField(default='nothing', max_length=2000000000),
        ),
    ]
