# Generated by Django 5.0.2 on 2024-03-16 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0008_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('A', 'Delicious'), ('B', 'Tasty'), ('C', 'Not Bad'), ('D', 'Worst')], max_length=1)),
                ('fooditem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodie.fooditems')),
            ],
        ),
    ]
