# Generated by Django 5.0.2 on 2024-03-26 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0013_category_fooditem_active_fooditem_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryList',
        ),
    ]
