# Generated by Django 5.0.2 on 2024-03-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0015_alter_fooditem_food_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_description',
            field=models.TextField(max_length=2000),
        ),
    ]
